http:
  middlewares:
    # Middleware applied globally at the entrypoint level (applied to all routers using "secure" entrypoint)
    security-headers:
      headers:
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 31536000

        referrerPolicy: "same-origin"
        featurePolicy: "vibrate 'self'; geolocation 'self'; midi 'self'; notifications 'self'; push 'self'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; vibrate 'self'; fullscreen 'self'"

        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true

        customresponseheaders:
          X-Frame-Options: sameorigin
          Content-Security-Policy: frame-ancestors https://*.{{ env "TRAEFIK_DOMAIN" }}
        customrequestheaders:
          X-Frame-Options: sameorigin
          Content-Security-Policy: frame-ancestors https://*.{{ env "TRAEFIK_DOMAIN" }}

    # Middlewares which are used automatically by the run-seedbox.sh script according to the parameters applied
    common-auth:
      basicAuth:
        usersFile: "/etc/traefik/http_auth"
    
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: false
    
    # crowdsec:
    #   plugin:
    #     bouncer:
    #       enabled: true
    #       defaultDecisionSeconds: 60
    #       crowdsecMode: live
    #       crowdsecAppsecEnabled: false # <--- here you can enable appsec waf
    #       crowdsecAppsecHost: crowdsec:7422
    #       crowdsecAppsecFailureBlock: true
    #       crowdsecAppsecUnreachableBlock: true
    #       crowdsecLapiKey: {{ env "CROWDSEC_LAPI_KEY" }}
    #       crowdsecLapiHost: crowdsec:8080
    #       crowdsecLapiScheme: http
    #       crowdsecLapiTLSInsecureVerify: false
    #       forwardedHeadersTrustedIPs:
    #         # private class ranges
    #         - 10.0.0.0/8
    #         - 172.16.0.0/12
    #         - 192.168.0.0/16
    #       clientTrustedIPs:
    #         # private class ranges
    #         - 10.0.0.0/8
    #         - 172.16.0.0/12
    #         - 192.168.0.0/16
    
    authelia:
      forwardAuth:
        address: http://authelia:9091/api/verify?rd=https://sso.{{ env "TRAEFIK_DOMAIN" }}
        trustForwardHeader: true
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"
    
    chain-authelia:
      chain:
        middlewares:
          - security-headers
          - authelia
