services:
  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    restart: unless-stopped
    volumes:
      - media:/data/media
      - bazarr-config:/config
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}

volumes:
  bazarr-config:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/bazarr