services:
  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: calibre
    restart: unless-stopped
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      # PASSWORD: ${UN1K0RN_PASSWORD}
      # CLI_ARGS: 
    volumes:
      - calibre-config:/config
      - media:/data/media

volumes:
  calibre-config: 
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/calibre
