services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    restart: unless-stopped
    volumes:
      - heimdall-config:/config
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}

volumes:
  heimdall-config:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/heimdall