services:
  komga:
    image: gotson/komga
    container_name: komga
    restart: unless-stopped
    volumes:
      - komga-config:/config
      - media:/data/media
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
    user: "${PUID}:${PGID}"

volumes:
  komga-config: 
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/komga