services:
  mylar:
    image: lscr.io/linuxserver/mylar3:latest
    container_name: mylar3
    restart: always
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - mylar-config:/config
      - torrents:/comics
      - downloads:/downloads

volumes:
  mylar-config: 
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/mylar
