services:
  netdata:
    image: netdata/netdata:stable
    restart: unless-stopped
    container_name: netdata
    hostname: netdata.${TRAEFIK_DOMAIN}
    environment:
      PGID: 999
      DOCKER_HOST: tcp://socket-proxy:2375
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    depends_on:
      - socket-proxy
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/os-release:/host/etc/os-release:ro
      # - /var/run/docker.sock:/var/run/docker.sock:ro
