services:
  nextcloud:
    depends_on:
      - mariadb
    image: linuxserver/nextcloud
    container_name: nextcloud
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - confignextcloud:/config
      - nextclouddata:/data
      - media:/data/media
      - config:/seedbox-config

volumes:
  confignextcloud:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/nextcloud
  nextclouddata:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/nextcloud-data
