services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - confignextcloud:/config
      - datanextcloud:/data
    depends_on:
      - postgres

volumes:
  confignextcloud:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/nextcloud
  datanextcloud:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/nextcloud-data
