services:
  ombi:
    image: ghcr.io/linuxserver/ombi
    container_name: ombi
    restart: unless-stopped
    volumes:
      - ombi-config:/config
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      BASE_URL: /

volumes:
  ombi-config:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/ombi