services:
  overseerr:
    image: ghcr.io/linuxserver/overseerr
    container_name: overseerr
    restart: unless-stopped
    volumes:
      - overseerr-config:/config
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      LOG_LEVEL: warn
    dns:
      - 1.1.1.1
      - 8.8.8.8

volumes:
  overseerr-config:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/overseerr
