services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      VERSION: docker
    volumes:
      - plex-config:/config
      - media:/data/media
    restart: unless-stopped
    shm_size: '4GB'

volumes:
  plex-config:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/plex
