services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/dri:/dev/dri # for hardware transcoding
    volumes:
      - plex-config:/config
      - media:/data/media
      - /dev/shm:/transcode
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - VERSION=latest

volumes:
  plex-config:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/Plex