services:
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    depends_on:
      - byparr
    volumes:
      - prowlarr-config:/config
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    restart: unless-stopped
  
  byparr:
    image: ghcr.io/thephaseless/byparr:main
    container_name: byparr
    init: true
    environment:
      TZ: ${TZ}
    restart: unless-stopped

volumes:
  prowlarr-config:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/prowlarr