services:
  qbittorrent:
    image: ghcr.io/hotio/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    volumes:
      - downloads:/data/media/downloads
      - qbittorrent-config:/config
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    mem_limit: 2g
    memswap_limit: 2g
    stop_grace_period: 30s
    blkio_config:
      weight: 200

volumes:
  qbittorrent-config: 
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/qbittorrent
