services:
  qbittorrent:
    image: ghcr.io/hotio/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    volumes:
      - downloads:/data/media/downloads
      - qbittorrent-config:/config
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}

volumes:
  qbittorrent-config: 
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/qbittorrent
