services:
  radarr:
    image: ghcr.io/linuxserver/radarr:develop
    container_name: radarr
    restart: unless-stopped
    volumes:
      - radarr-config:/config
      - media:/data/media
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}

volumes:
  radarr-config: 
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/radarr