services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr:develop
    container_name: sonarr
    restart: unless-stopped
    volumes:
      - sonarr-config:/config
      - media:/data/media
      - /etc/localtime:/etc/localtime:ro
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}


volumes:
  sonarr-config: 
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/sonarr
