services:
  syncthing:
    image: lscr.io/linuxserver/syncthing
    container_name: syncthing
    restart: unless-stopped
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    volumes:
      - syncthing-config:/config
      - media:/data/media
      - config:/allconfig
    ports:
    #   #- 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp

volumes:
  syncthing-config: 
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/configsyncthing