services:
  tautulli:
    image: ghcr.io/linuxserver/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - tautulli-config:/config
      - plex-config:/plex:ro # Inside of tautulli, bind to logs via "/logs/Plex Media Server/Logs"
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}

volumes:
  tautulli-config:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/tautulli
